# Name of workflow as seen in Github actions tab
name: dev-build-and-deploy
# Run workflow only on push to dev branch
on:
  push:
    branches:
      - master
jobs:
  # To build the project
  build-lumify:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out code
        uses: actions/checkout@v3
      - name: Installing Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "13.x"
      - name: Installing dependencies
        run: npm install
      - run: npm install i18n-iso-countries
      - run: npm install bcryptjs@2.4.3
      - run: npm install crypto-browserify@3.12.0
      - run: npx browserslist@latest --update-db
      - name: Building project
        run: CI=false npm run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Deploy to S3 bucket
        run: aws s3 sync ./build/ s3://test-lumify --delete
